
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 11 22:01:47 CEST 2025
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int OP_MENOR = 12;
  public static final int BOOL = 70;
  public static final int REAL = 69;
  public static final int MENOR_IGUAL = 27;
  public static final int EXCLAMACION = 2;
  public static final int OP_INTERROGACION = 16;
  public static final int SUMA_PREF = 23;
  public static final int CONST = 52;
  public static final int OP_MULT = 6;
  public static final int P_CIE = 5;
  public static final int OP_MOD = 35;
  public static final int UNTIL = 42;
  public static final int P_AP = 4;
  public static final int FUNC = 37;
  public static final int ELSIF = 41;
  public static final int IDEN = 57;
  public static final int OP_SUMA = 7;
  public static final int OP_RESTA = 9;
  public static final int IN_BOOL = 64;
  public static final int OP_DIV_REAL = 25;
  public static final int STRUCT = 46;
  public static final int IN_REAL = 62;
  public static final int DISTINTO = 21;
  public static final int IGUAL_IGUAL = 28;
  public static final int ARRAY = 40;
  public static final int PUNT = 39;
  public static final int COMO = 48;
  public static final int NUM_REAL = 59;
  public static final int MULT_PREF = 22;
  public static final int NUM_ENTERO = 58;
  public static final int TO_ENT = 55;
  public static final int DOLLAR = 3;
  public static final int COMA = 8;
  public static final int ALIAS = 49;
  public static final int MOD_PREF = 38;
  public static final int WHILE = 43;
  public static final int TO_REAL = 54;
  public static final int DIV_ENT_PREF = 26;
  public static final int C_CIE = 18;
  public static final int FOR = 34;
  public static final int V = 67;
  public static final int OP_MAYOR = 14;
  public static final int VOID = 47;
  public static final int RETURN = 45;
  public static final int ELSE = 36;
  public static final int OUT_ENT = 61;
  public static final int F = 68;
  public static final int EOF = 0;
  public static final int OP_AND = 33;
  public static final int RESTA_PREF = 24;
  public static final int OP_ACCESO = 10;
  public static final int LL_CIE = 20;
  public static final int REPEAT = 44;
  public static final int LL_AP = 19;
  public static final int OP_DOS_PUNTOS = 56;
  public static final int MAIN = 53;
  public static final int DIV_REAL_PREF = 32;
  public static final int ENT = 66;
  public static final int OP_ARROBA = 15;
  public static final int error = 1;
  public static final int OP_PUNTO_COMA = 71;
  public static final int IF = 31;
  public static final int C_AP = 17;
  public static final int IN_ENT = 60;
  public static final int NEW = 50;
  public static final int OP_IGUAL = 13;
  public static final int OP_DIV_ENT = 11;
  public static final int OUT_BOOL = 65;
  public static final int OUT_REAL = 63;
  public static final int TO = 51;
  public static final int OP_OR = 30;
  public static final int MAYOR_IGUAL = 29;
}

