package ast.Linea;

public enum KindAsig{
	ASIG, SUMAPREF, RESTAPREF, MULTPREF, DIVREALPREF, MODPREF, DIVENTPREF, ELEVARPREF, ACCESO, PUNTERO, DOLLAR, ARROBA, EXCLAM, AND, OR, CORCH, PAR, LLAVE, POR, DIVENT, MOD, DIVREAL, MAS, MENOS, NEG, ELEVAR, MAYOR, MENOR, MAYORIG, MENORIG, IGUALIG, DISTINTO, TOREAL, TOENT, LLAMADA, UNITARIO, REAL, ENT, BOOL, DINAMICA, INTERROGACION;
}